"""add image field

Revision ID: 14a22777fab1
Revises: f19f34be0aaf
Create Date: 2023-11-09 00:11:29.100059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a22777fab1'
down_revision = 'f19f34be0aaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dream', sa.Column('image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dream', 'image')
    # ### end Alembic commands ###
