"""add name field to User

Revision ID: 272f0dfbd069
Revises: 88bf2f4b5a6f
Create Date: 2023-10-27 05:24:05.642606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272f0dfbd069'
down_revision = '88bf2f4b5a6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
