"""change user_id unique

Revision ID: 88bf2f4b5a6f
Revises: 9ff9c3ec6de9
Create Date: 2023-10-23 02:50:01.764276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88bf2f4b5a6f'
down_revision = '9ff9c3ec6de9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_dream_user_id', 'dream', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_dream_user_id', 'dream', ['user_id'])
    # ### end Alembic commands ###
