"""add category field

Revision ID: 8b445588b366
Revises: 344a548310c3
Create Date: 2025-08-27 14:46:58.685977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b445588b366'
down_revision = '344a548310c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dream', sa.Column('category', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dream', 'category')
    # ### end Alembic commands ###
