"""initial dream model

Revision ID: 9ff9c3ec6de9
Revises: 8e093998ef28
Create Date: 2023-10-23 02:16:39.486505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff9c3ec6de9'
down_revision = '8e093998ef28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dream',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dream')),
    sa.UniqueConstraint('user_id', name=op.f('uq_dream_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dream')
    # ### end Alembic commands ###
