"""remove unused fields

Revision ID: ab9a166dde12
Revises: df02efdbef31
Create Date: 2023-11-18 06:01:37.765969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9a166dde12'
down_revision = 'df02efdbef31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dreamlikedrecord', sa.Column('author_username_id', sa.Text(), nullable=True))
    op.add_column('dreamlikedrecord', sa.Column('liked_username_id', sa.Text(), nullable=True))
    op.drop_column('dreamlikedrecord', 'author_user_id')
    op.drop_column('dreamlikedrecord', 'liked_user_id')
    op.drop_column('dreamlikedrecord', 'liked_username')
    op.drop_column('dreamlikedrecord', 'author_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dreamlikedrecord', sa.Column('author_username', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('dreamlikedrecord', sa.Column('liked_username', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('dreamlikedrecord', sa.Column('liked_user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('dreamlikedrecord', sa.Column('author_user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('dreamlikedrecord', 'liked_username_id')
    op.drop_column('dreamlikedrecord', 'author_username_id')
    # ### end Alembic commands ###
