"""add performance indexes

Revision ID: add_performance_indexes
Revises: f19a34be0aaf
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_performance_indexes'
down_revision = 'f19a34be0aaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Индекс для быстрого поиска желаний по user_id
    op.create_index('ix_dream_user_id', 'dream', ['user_id'])
    
    # Индекс для быстрого поиска пользователей по user_id
    op.create_index('ix_user_user_id', 'user', ['user_id'])
    
    # Индекс для быстрого поиска по дате создания
    op.create_index('ix_dream_created_at', 'dream', ['created_at'])
    
    # Составной индекс для оптимизации пагинации
    op.create_index('ix_dream_user_created', 'dream', ['user_id', 'created_at'])
    
    # Индекс для поиска по типу обратной связи
    op.create_index('ix_dream_liked_record_type', 'dream_liked_record', ['type_feedback'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index('ix_dream_user_created', table_name='dream')
    op.drop_index('ix_dream_created_at', table_name='dream')
    op.drop_index('ix_user_user_id', table_name='user')
    op.drop_index('ix_dream_user_id', table_name='dream')
    op.drop_index('ix_dream_liked_record_type', table_name='dream_liked_record')
    
    # ### end Alembic commands ###
