"""add DreamLikedRecord

Revision ID: df02efdbef31
Revises: 14a22777fab1
Create Date: 2023-11-18 05:57:37.514325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df02efdbef31'
down_revision = '14a22777fab1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dreamlikedrecord',
    sa.Column('author_user_id', sa.BigInteger(), nullable=False),
    sa.Column('author_username', sa.Text(), nullable=True),
    sa.Column('liked_user_id', sa.BigInteger(), nullable=False),
    sa.Column('liked_username', sa.Text(), nullable=True),
    sa.Column('dream_name', sa.Text(), nullable=True),
    sa.Column('type_feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dreamlikedrecord'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dreamlikedrecord')
    # ### end Alembic commands ###
