"""add new field for Dream

Revision ID: f19f34be0aaf
Revises: 272f0dfbd069
Create Date: 2023-11-05 07:48:13.802128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19f34be0aaf'
down_revision = '272f0dfbd069'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dream', sa.Column('username', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dream', 'username')
    # ### end Alembic commands ###
